### ISSUE TITLE
[goexoml/buildgenerator] Optimise generator

### ISSUE THREAD

**Issue by sarathsp06** [exotel/goexoml#4]
Optimise generator, following is one issue in [generator](https://github.com/exotel/goexoml/tree/master/buildergenerator)  that needs an urgent fix

*  update the Setter generator to not create `switch` statements if there are no Fields in the struct to be generated. Eg: [Hangup](https://github.com/exotel/goexoml/blob/master/hangup_builder.go#L13)

**Comment by marcosnils** [comment]
I can give this a try.
